### PR TITLE
Golf

### PR DESCRIPTION
**Pull request by AdamSpannbauer**
Info:
* Hole location - random height and random x on right side of screen
* Ball location - random height and random x on left side of screen
* initial aim - random between [-half_pi, half_pi] (always on the right side of vertical but in rare cases can point straight up/down)
* always same ball speed and rotation speed
* game won when `this.distToHole < this.hole.r - this.ball.r`

Controls:
* left arrow key to rotate counter clockwise
* right arrow key to rotate clockwise
* space bar to hit ball

Gameplay:
golfDemo

### CODE REVIEW

**Review by JaysonRice — APPROVED** [review]
Works great, my only complaint is I tried to use the up arrow on the first play.

**Comment by AdamSpannbauer** [comment]
Should we put a graphic with like:

```
<left arrow icon> <counter clockwise refresh button looking icon>
<right arrow icon> <clockwise refresh button looking icon>
```

**Comment by AdamSpannbauer** [comment]
Or would it be better to make both up and left arrows be counter clockwise and both down and right arrows clockwise? Would be a super easy option. 

Thoughts on displaying more info vs this alternative @JaysonRice ?

**Comment by JaysonRice** [comment]
I like the second option more, but I wanna use that logic in a MS paint example. Holding ↑ for the ball on the left would make the line travel downwards, but not for the ball on the right. I think it's more intuitive for the up key to always have the line travel towards 0° and 180° for the down key. Or we can do info option.mspain

**Comment by AdamSpannbauer** [comment]
Rn the ball can only appear on the left so I think we avoid the issue you mention (read and responded to at yeehaw tho so I might've missed some points)

**Pull request merged**
